services:
  db:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: egallery
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: e-gallery
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy

  migrate:
    build: .
    container_name: e-gallery-migrate
    command: npx drizzle-kit push
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
