import NextTopLoader from "nextjs-toploader";

import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "@/components/ui/sonner";

export const Metadata = {
  title: "E-Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <div className="max-h-[5vh] ">
            <NextTopLoader color="#ef233c" />
            <Navbar />
          </div>
          <div className="h-[95vh] pt-[5vh] ">{children}</div>
          <Toaster richColors />
        </body>
      </html>
    </SessionWrapper>
  );
}
